experiment_name: 'temp_model_1'
is_overfit: True
device: 'cuda:0'
max_epochs: 100
train_batch_size: 32
val_batch_size: 16
learning_rate: 0.0008
resume_ckpt: False
print_every_n: 1
validate_every_n: 1
