base_path: 'C:/Users/aorhu/Masaüstü/ML3DG_Project/3d-segmentation-in-2d/runs'
pt_model_path: 'C:/Users/aorhu/models/model.ckpt'
experiment_name: 'temp_model_1'
is_overfit: False
device: 'cuda:0'
max_epochs: 100
train_batch_size: 4
val_batch_size: 1
learning_rate: 0.0001
resume_ckpt: False
print_every_n: 1000
validate_every_n: 500
ckpt_path: "C:/Users/aorhu/3d-segmentation-in-2d/runs/training_lr05_35epoch/model_best.ckpt"
num_workers: 0
