base_path: 'C:/Users/aorhu/3d-segmentation-in-2d/runs/'
pt_model_path: 'C:/Users/aorhu/3d-segmentation-in-2d/runs/training_100_lr01_37epoch/model_best.ckpt'
experiment_name: 'training_lr05_c'
is_overfit: False
device: 'cuda:0'
max_epochs: 100
train_batch_size: 8
val_batch_size: 2
learning_rate: 0.00005
resume_ckpt: True
ckpt_path: "C:/Users/aorhu/3d-segmentation-in-2d/runs/training_lr05_35epoch/model_best.ckpt"
print_every_n: 250
validate_every_n: 250
num_workers: 0
