base_path: 'C:/Users/aorhu/3d-segmentation-in-2d/runs/'
pt_model_path: 'C:/Users/aorhu/models/model.ckpt'
experiment_name: 'overfit'
is_overfit: True
device: 'cuda:0'
max_epochs: 100
train_batch_size: 4
val_batch_size: 1
learning_rate: 0.0005
resume_ckpt: False
print_every_n: 1
validate_every_n: 1
num_workers: 0
