base_path: 'C:/Users/aorhu/3d-segmentation-in-2d/runs/'
pt_model_path: 'C:/Users/aorhu/models/model.ckpt'
experiment_name: 'overfit'
is_overfit: True
device: 'cuda:0'
max_epochs: 100
train_batch_size: 8
val_batch_size: 2
learning_rate: 0.0005
resume_ckpt: False
ckpt_path: ""
print_every_n: 250
validate_every_n: 250
num_workers: 0
idx_class: 5
idx_class_sample: 1
export: False
on_Jupyter: True
