experiment_name: 'experiment_1'
is_overfit: False
device: 'cuda:0'
num_workers: 0
max_epochs: 100
train_batch_size: 4
val_batch_size: 1
learning_rate: 0.0001
resume_ckpt: False
print_every_n: 100
validate_every_n: 100
