name: 3d-seg-in-2d
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=1.12
  - nomkl
  - h5py
  - networkx
  - scipy
  - scikit-learn
  - wandb
  - tqdm
  - plotly
  - seaborn
  # dev dependencies
  - pre-commit
